---
- name: "nxos.arp: show ip arp statistics"
  cli_parse_transform:
    engine: "native_json"
    commands:
      - command: "show ip arp statistics"
        set_fact: True
        transform:
        - name: "nxos_flatten_table_row"
        - name: set_root_key
          key: "ip_arp_statistics"

- name: "nxos.arp: show ip arp vrf all"
  cli_parse_transform:
    engine: "native_json"
    commands:
      - command: "show ip arp vrf all"
        set_fact: True
        transform:
        - name: "nxos_flatten_table_row"
        - name: set_root_key
          key: "ip_arp_vrf_all"
