---
- name: "nxos.cdp: show cdp global"
  ignore_errors: "{{ layer2_ignore_errors }}"
  cli_parse_transform:
    engine: "native_json"
    commands:
      - command: "show cdp global"
        set_fact: True
        transform:
        - name: "nxos_flatten_table_row"
        - name: set_root_key
          key: cdp_global

- name: "nxos.cdp: show cdp neighbors"
  ignore_errors: "{{ layer2_ignore_errors }}"
  cli_parse_transform:
    engine: "native_json"
    commands:
      - command: "show cdp neighbors"
        set_fact: True
        transform:
        - name: "nxos_flatten_table_row"
        - name: set_root_key
          key: cdp_neighbors

- name: "nxos.cdp: show cdp neighbors detail"
  ignore_errors: "{{ layer2_ignore_errors }}"
  cli_parse_transform:
    engine: "native_json"
    commands:
      - command: "show cdp neighbors"
        set_fact: True
        transform:
        - name: "nxos_flatten_table_row"
        - name: set_root_key
          key: cdp_neighbors_detail
