---
- name: "nxos.fex: show fex"
  ignore_errors: "{{ layer2_ignore_errors }}"
  cli_parse_transform:
    engine: "native_json"
    commands:
      - command: "show fex"
        set_fact: True
        transform:
        - name: "nxos_flatten_table_row"
        - name: set_root_key
          key: "fex"

- name: "nxos.fex: show fex detail"
  ignore_errors: "{{ layer2_ignore_errors }}"
  cli_parse_transform:
    engine: "native_json"
    commands:
      - command: "show fex"
        set_fact: True
        transform:
        - name: "nxos_flatten_table_row"
        - name: set_root_key
          key: "fex_detail"