---
- name: "nxos.interface: show interface status err-disabled"
  ignore_errors: "{{ layer2_ignore_errors }}"
  cli_parse_transform:
    engine: "native_json"
    commands:
    - command: "show interface status err-disabled"
      set_fact: False
      transform:
      - name: "str_to_native"
      - name: "nxos_flatten_table_row"
      - name: set_root_key
        key: interface_status_err__disabled

- name: "nxos.interface: show interface counters errors"
  ignore_errors: "{{ layer2_ignore_errors }}"
  cli_parse_transform:
    engine: "native_json"
    commands:
    - command: "show interface counters errors"
      set_fact: False
      transform:
      - name: "str_to_native"
      - name: "nxos_flatten_table_row"
      - name: set_root_key
        key: interface_counters_errors

- name: "nxos.interface: show interface status"
  ignore_errors: "{{ layer2_ignore_errors }}"
  cli_parse_transform:
    engine: "native_json"
    commands:
    - command: "show interface status"
      set_fact: False
      transform:
      - name: "nxos_flatten_table_row"
      - name: set_root_key
        key: interface_status

- name: "nxos.interface: show interface switchport"
  ignore_errors: "{{ layer2_ignore_errors }}"
  cli_parse_transform:
    engine: "native_json"
    commands:
    - command: "show interface switchport"
      set_fact: False
      transform:
      - name: "nxos_flatten_table_row"
      - name: set_root_key
        key: interface_switchport

- name: "nxos.interface: show interface trunk"
  ignore_errors: "{{ layer2_ignore_errors }}"
  cli_parse_transform:
    engine: "native_json"
    commands:
    - command: "show interface trunk"
      set_fact: False
      transform:
      - name: "nxos_flatten_table_row"
      - name: set_root_key
        key: interface_trunk

- name: "nxos.interface: show interface transceiver"
  ignore_errors: "{{ layer2_ignore_errors }}"
  cli_parse_transform:
    engine: "native_json"
    commands:
    - command: "show interface transceiver"
      set_fact: False
      transform:
      - name: "nxos_flatten_table_row"
      - name: set_root_key
        key: interface_transceiver
