---
- name: "nxos.lldp: show lldp neighbors"
  cli_parse_transform:
    engine: "native_json"
    commands:
      - command: "show lldp neighbor"
        set_fact: True
        transform:
        - name: "nxos_flatten_table_row"
        - name: set_root_key
          key: lldp_neighbors

- name: "nxos.lldp: show lldp neighbors"
  cli_parse_transform:
    engine: "native_json"
    commands:
      - command: "show lldp neighbors detail"
        set_fact: True
        transform:
        - name: "nxos_flatten_table_row"
        - name: set_root_key
          key: lldp_neighbors_detail
