---
- name: "nxos.mlag: show vpc"
  ignore_errors: "{{ layer2_ignore_errors }}"
  cli_parse_transform:
    engine: "native_json"
    commands:
      - command: "show vpc"
        set_fact: True
        transform:
        - name: "nxos_flatten_table_row"
        - name: set_root_key
          key: "vpc"

- name: "nxos.mlag: show vpc consistency-parameters global"
  ignore_errors: "{{ layer2_ignore_errors }}"
  cli_parse_transform:
    engine: "native_json"
    commands:
      - command: "show vpc consistency-parameters global"
        set_fact: True
        transform:
        - name: "nxos_flatten_table_row"
        - name: set_root_key
          key: "vpc_consistency__parameters_global"

- name: "nxos.mlag: show vpc consistency-parameters vlans"
  ignore_errors: "{{ layer2_ignore_errors }}"
  cli_parse_transform:
    engine: "native_json"
    commands:
      - command: "show vpc consistency-parameters vlans"
        set_fact: True
        transform:
        - name: "nxos_flatten_table_row"
        - name: set_root_key
          key: "vpc_consistency__parameters_vlans"
