---
- name: "nxos.mlag: show vpc"
  cli_parse_transform:
    engine: "native_json"
    commands:
      - command: "show vpc"
        set_fact: True
        transform:
        - name: "nxos_flatten_table_row"
        - name: set_root_key
          key: "vpc"
