---
- name: "nxos.spanning_tree: show spanning-tree blockedports"
  ignore_errors: "{{ layer2_ignore_errors }}"
  cli_parse_transform:
    engine: "native_json"
    commands:
      - command: "show spanning-tree blockedports"
        set_fact: True
        transform:
        - name: "nxos_flatten_table_row"
        - name: set_root_key
          key: spanning__tree_blockedports

- name: "nxos.spanning_tree: show spanning-tree inconsistentports"
  ignore_errors: "{{ layer2_ignore_errors }}"
  cli_parse_transform:
    engine: "native_json"
    commands:
      - command: "show spanning-tree inconsistentports"
        set_fact: True
        transform:
        - name: "nxos_flatten_table_row"
        - name: set_root_key
          key: spanning__tree_inconsistentports

- name: "nxos.spanning_tree: show spanning-tree active detail"
  ignore_errors: "{{ layer2_ignore_errors }}"
  cli_parse_transform:
    engine: "native_json"
    commands:
      - command: "show spanning-tree forwarding"
        set_fact: True
        transform:
        - name: "nxos_flatten_table_row"
        - name: set_root_key
          key: spanning__tree_active_detail

- name: "nxos.spanning_tree: show spanning-tree root detail"
  ignore_errors: "{{ layer2_ignore_errors }}"
  cli_parse_transform:
    engine: "native_json"
    commands:
      - command: "show spanning-tree root detail"
        set_fact: True
        transform:
        - name: "nxos_flatten_table_row"
        - name: set_root_key
          key: spanning__tree_root_detail
