---
- name: "nxos.system: show system resources"
  ignore_errors: "{{ layer2_ignore_errors }}"
  cli_parse_transform:
    engine: "native_json"
    commands:
      - command: "show system resources"
        set_fact: True
        transform:
        - name: "str_to_native"
        - name: "nxos_flatten_table_row"
        - name: set_root_key
          key: show_system_resources
