---
- name: "nxos.vlan: show vlan"
  cli_parse_transform:
    engine: "native_json"
    commands:
      - command: "show vlan"
        set_fact: True
        transform:
        - name: "nxos_flatten_table_row"
        - name: set_root_key
          key: vlan

- name: "nxos.vlan: show vlan private-vlan"
  cli_parse_transform:
    engine: "native_json"
    commands:
      - command: "show vlan private-vlan"
        set_fact: True
        transform:
        - name: "nxos_flatten_table_row"
        - name: set_root_key
          key: vlan_private__vlan
