---
- name: "tasks: call os/platform/version specific tasks"
  include_tasks: "{{ item }}"
  with_first_found:
    - skip: true
      files:
        # yamllint disable-line rule:line-length
        - "{{ layer2_os }}/{{ layer2_platform }}/{{ layer2_version }}/{{ layer2_function }}.yaml"
        # yamllint disable-line rule:line-length
        - "{{ layer2_os }}/{{ layer2_platform }}/{{ layer2_function }}.yaml"
        - "{{ layer2_os }}/{{ layer2_function }}.yaml"
        - "{{ layer2_os }}/main.yaml"
