---
- name: "tasks: load os/platform/version specific variables"
  include_vars: "{{ item }}"
  with_first_found:
    - skip: true
      files:
        # yamllint disable-line rule:line-length
        - "{{ layer2_os }}/{{ layer2_platform }}/{{ layer2_version }}.yaml"
        - "{{ layer2_os }}/{{ layer2_platform }}.yaml"
        - "{{ layer2_os }}/main.yaml"
        - "main.yaml"
      paths:
        - "../vars/"
