---
- name: "nxos.arp: show ip arp vrf all"
  cli_parse_transform:
    engine: "native_json"
    commands:
      - command: "show ip arp vrf all"
        set_fact: True
        transform:
        - name: "nxos_flatten_table_row"

- name: "nxos.arp: assert entry"
  assert:
    that: 
    - "desired arp entry is present..."
