---
- name: "nxos.arp: show ip arp {{ checkmate_ip_address }} vrf all"
  cli_parse_transform:
    engine: "native_json"
    commands:
      - command: "show ip arp {{ checkmate_ip_address }} vrf all"
        set_fact: True
        transform:
        - name: "nxos_flatten_table_row"
        - name: set_root_key
          key: "show_ip_arp_address_vrf_all"

- name: "nxos.mac: assert ip arp {{ checkmate_ip_address }} vrf all"
  ignore_errors: true
  vars:
    arp_address: "{{ ansible_facts['show_ip_arp_address_vrf_all'] }}"
  assert:
    that:  arp_address[0] == checkmate_mac_address
