---
- name: "nxos.mac: show mac address-table address {{ checkmate_mac_address }}"
  cli_parse_transform:
    engine: "native_json"
    commands:
      - command: "show mac address-table address {{ checkmate_mac_address }}"
        set_fact: True
        transform:
        - name: "nxos_flatten_table_row"
        - name: set_root_key
          key: "show_mac_address__table_address"

- name: "nxos.mac: assert mac address-table address {{ checkmate_mac_address }}"
  ignore_errors: true
  vars:
    mac_address: "{{ ansible_facts['show_mac_address__table_address']['mac_address'] }}"
  assert:
    that:  mac_address[0] == checkmate_mac_address
