---
- name: "nxos.spanning_tree: show spanning-tree blockedports"
  cli_parse_transform:
    engine: "native_json"
    commands:
      - command: "show spanning-tree blockedports"
        set_fact: True
        transform:
        - name: "nxos_flatten_table_row"
        - name: set_root_key
          key: show_spanning__tree_blockedports

- name: "nxos.spanning_tree: assert spanning-tree blockedports"
  ignore_errors: true
  vars:
    spanning_tree_blockedports: "{{ ansible_facts['show_spanning__tree_blockedports'] }}"
  assert:
    that: spanning_tree_blockedports is string

- name: "nxos.spanning_tree: show spanning-tree inconsistentports"
  cli_parse_transform:
    engine: "native_json"
    commands:
      - command: "show spanning-tree inconsistentports"
        set_fact: True
        transform:
        - name: "nxos_flatten_table_row"
        - name: set_root_key
          key: show_spanning__tree_inconsistentports

- name: "nxos.spanning_tree: assert spanning-tree blockedports"
  ignore_errors: true
  vars:
    spanning_tree_inconsistentports: "{{ ansible_facts['show_spanning__tree_inconsistentports'] }}"
  assert:
    that: spanning_tree_inconsistentports is string
