---
- name: "nxos.system: show system resources"
  cli_parse_transform:
    engine: "native_json"
    commands:
      - command: "show system resources"
        set_fact: True
        transform:
        - name: "str_to_native"
        - name: "nxos_flatten_table_row"
        - name: set_root_key
          key: show_system_resources

- name: "nxos.system: assert system resources"
  ignore_errors: true
  vars:
    system_resources: "{{ ansible_facts['show_system_resources'] }}"
  assert:
    that: 
    - system_resources['cpu_state_idle'] >= 20
    - system_resources['memory_usage_used'] <= (system_resources['memory_usage_total'] * 0.80)
    - system_resources['current_memory_status'] == 'OK'
