---
- name: "nxos.link.counters: show interface counters errors (before)"
  cli_parse_transform:
    engine: "native_json"
    commands:
    - command: "show interface counters errors"
      set_fact: False
      transform:
      - name: "str_to_native"
      - name: "nxos_flatten_table_row"
      - name: set_root_key
        key: show_interface_counters_errors_before

- name: "nxos.link.counters: wait for 60 seconds"
  wait_for:
    timeout: 60

- name: "nxos.link.counters: show interface counters errors (after)"
  cli_parse_transform:
    engine: "native_json"
    commands:
    - command: "show interface counters errors"
      set_fact: False
      transform:
      - name: "str_to_native"
      - name: "nxos_flatten_table_row"
      - name: set_root_key
        key: show_interface_counters_errors_after

- name: "nxos.link.counters: assert interface counters errors (before and after)"
  ignore_errors: true
  vars:
    interface_counters_errors_before: "{{ ansible_facts['show_interface_counters_errors_before'] }}"
    interface_counters_errors_after: "{{ ansible_facts['show_interface_counters_errors_after'] }}"
  assert:
    that: interface_counters_errors_before == interface_counters_errors_after
