---
- name: "Layer2"
  connection: network_cli
  hosts: all
  gather_facts: false
  roles:
    - role: "victorock.jetpack"
    - role: "layer2"
      collectors:
        - 'arp'
        - 'cdp'
        - 'interface'
        - 'lldp'
        - 'mac'
        - 'mlag'
        - 'spanning_tree'
        - 'system'
        - 'vlan'

